# Generated by Django 6.1.1 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('is_finished', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
